services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - REACT_APP_BACKEND_HOST=${REACT_APP_BACKEND_HOST}
        - REACT_APP_BACKEND_PORT=${REACT_APP_BACKEND_PORT}
        - REACT_APP_API_KEY=${REACT_APP_API_KEY}
    ports:
      - "${REACT_APP_FRONTEND_PORT}:80"
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "${REACT_APP_BACKEND_PORT}:${REACT_APP_BACKEND_PORT}"
    environment:
      - REACT_APP_BACKEND_HOST=0.0.0.0
      - REACT_APP_BACKEND_PORT=${REACT_APP_BACKEND_PORT}