name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Services
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.24
        options: >-
          --privileged
          --entrypoint /bin/sh
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build backend image
      - name: Build Backend Image
        run: |
          set -e
          echo "Building backend Docker image..."
          docker compose build backend || {
            echo "Backend image build failed!";
            exit 1;
          }

      # Build frontend image
      - name: Build Frontend Image
        run: |
          set -e
          echo "Building frontend Docker image..."
          docker compose build frontend || {
            echo "Frontend image build failed!";
            exit 1;
          }

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Start application
      - name: Start Services with Docker Compose
        run: |
          echo "Starting application with Docker Compose..."
          docker compose up -d || {
            echo "Failed to start application!";
            exit 1;
          }

      # Run tests using environment variables for ports
      - name: Run Integration Tests
        run: |
          #Load environment variables from .env file
          set -o allexport
          source .env
          set +o allexport

          echo "Running integration tests..."
          echo "Backend port: $REACT_APP_BACKEND_PORT"
          echo "Frontend port: $REACT_APP_FRONTEND_PORT"
          docker ps
          sleep 10
          curl -f http://localhost:$REACT_APP_BACKEND_PORT/api || {
            echo "Backend test failed!";
            exit 1;
          }
          curl -f http://localhost:$REACT_APP_FRONTEND_PORT || {
            echo "Frontend test failed!";
            exit 1;
          }

      # Shut down services
      - name: Stop Services
        run: |
          echo "Stopping application..."
          docker compose down || {
            echo "Failed to stop application!";
            exit 1;
          }
